print ("Biodata")
print ("Nama : Akhlaqul Karimah")
print ("Nama Panggilan : Rima")
print ("Alamat : Celep Utara RT.03 RW.01 Sidoarjo")
print ("Asal Sekolah : Diploma III Statistika ITS")
print ("Nama FB : Akhlaqul Karimah")
print ("Nama IG : @akhlaqul_k")
print ("Nomor HP : 083830180290")
print ("Email : akhlaqul.karimah18@gmail.com")
